spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-02.cleardb.com/heroku_3b0d2de316c7b12?reconnect=true
    username: b595066b975e7f
    password: b535c843

  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true

  mail:
    host: smtp.gmail.com
    username: ${UDEMYSBHRESTIJWTS3MSQLMDB3_USERNAME:udemysbhrestijwts3msqlmdb3}
    password: ${UDEMYSBHRESTIJWTS3MSQLMDB3_PASSWORD:4Jg5g@3VZbI!F^5xw29xaB}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false