spring:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true


  datasource:
    platform: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  # data:
  #   web:
  #     pageable:
  #       default-page-size: 24