spring:
  datasource:
    url: jdbc:mysql://localhost:3306/udemysbhrestijwts3msqlmdb3
    username: root
    password: root

  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true

  mail:
    host: smtp.gmail.com
    username: ${UDEMYSBHRESTIJWTS3MSQLMDB3_USERNAME:udemysbhrestijwts3msqlmdb3}
    password: ${UDEMYSBHRESTIJWTS3MSQLMDB3_PASSWORD:4Jg5g@3VZbI!F^5xw29xaB}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false