spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-02.cleardb.com/heroku_3b0d2de316c7b12?reconnect=true
    username: b595066b975e7f
    password: b535c843

  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true