spring:
  profiles:
    active:
    - dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}


default:
  sender: ${DEFAULT_SENDER}
  recipient: ${DEFAULT_RECIPIENT}

jwt.secret: SequenciaDeCaracteresParaAssinarToken
jwt.expiration: 86400000

aws:
  access_key_id: ${AWS_ID}
  secret_access_key: ${AWS_KEY}
s3:
  bucket: udemy-sbhrestijwts3msqlmdb3
  region: sa-east-1

img.prefix.client.profile: cp
img.profile.size: 200