spring:
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true

  datasource:
    platform: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:mem:udemysbhrestijwts3msqlmdb3test
    username: sa
    password:
    driver-class-name: org.h2.Driver