spring:
  datasource:
    platform: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:mem:udemysbhrestijwts3msqlmdb3
    username: sa
    password:

  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true