spring:
  datasource:
    url: jdbc:mysql://mariadb:3306/udemysbhrestijwts3msqlmdb3
    username: root
    password: root

  jpa:
    database: mysql
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true

  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false