spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root

  jpa:
    database: mysql
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

    properties:
      hibernate.format_sql: true